swagger: "2.0"
info:
  version: 1.0.0
  title: NodeBase
  description: BaseProject
basePath: /api/
tags:
  - name: Examples
    description: Simple example endpoints
  - name: Specification
    description: The swagger API specification

consumes:
  - application/json
produces:
  - application/json


definitions:
  ExampleBody:
    type: object
    title: user
    required:
      - name
    properties:
      firstName:
        type: string
        example: FirstName
      lastName:
        type: string
        example: LastName
      email:
        type: string
        example: email
      password:
        type: string
        example: password

paths:
  /users/register:
    get:
      tags:
        - Examples
      description: Fetch all examples
      responses:
        200:
          description: Returns all examples
    post:
      tags:
        - User
      description: Create a new user
      parameters:
        - name: user
          in: body
          description: an user signup
          required: true
          schema: 
            $ref: "#/definitions/ExampleBody"
      responses:
        200:
          description: Returns all examples

  /examples/{id}:
    get:
      tags:
        - Examples
      parameters:
        - name: id
          in: path
          required: true
          description: The id of the example to retrieve
          type: integer
      responses:
        200:
          description: Return the example with the specified id
        404:
          description: Example not found

  /spec:
    get:
      tags:
        - Specification
      responses:
        200:
          description: Return the API specification